### ISSUE TITLE
Excplain how to exacly compile it...

### ISSUE THREAD

**Issue by PavelPoltavets** [Aqua-Vision/MgKex#1]
I have istalled VS2019 and windows 7.1 sdk that added to VS "v100" compilation way...
But I have a lot of different errors depending on what I am doing next...
some of them - 
+ MSB8003: Could not find WindowsSDKDir variable from the registry. TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. and Windows.h not founded...

+ LNK1123 failure during conversion to COFF: file invalid or corrupt 1	(it fixes by removing .rc files from project but thai is not an option..,)
 
 + Required file "" is missing.	for KexPathCch in C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets	147	
 
 + and some another that says something like "cannot find KexPathCch.lib" etc...
 
 so what is your dependancy configuration and other things to compile it?

**Comment by Aqua-Vision** [comment]
This solution is meant to be compiled with Visual Studio 2010. You can download it here for free:

https://archive.org/details/en_vs_2010_ult

![image](https://github.com/user-attachments/assets/dc6a0054-9ccf-452c-a038-68b24e18f4de)

**Comment by Aqua-Vision** [comment]
I will add compilation instructions to the README file shortly.

**Comment by PavelPoltavets** [comment]
Well by installing all from the site you gave me I can compile the project on vs2019, but another fork of VxKex (https://github.com/OneForgottenMan/VxKex)... Thanks you in any case...
