### ISSUE TITLE
Python 3.13 Error (I fixed it)

### ISSUE THREAD

**Issue by YuZhouRen86** [Aqua-Vision/MgKex#11]
Python 3.13 cannot import package from PATH, and Python embbed cannot launch. This is an annoying bug to Python developers.
![图片](https://github.com/user-attachments/assets/b1180751-0591-403f-b7ec-3e2435605bfe)
12/10 UPDATE: I fixed it by using some of the code in https://github.com/nalexandru/api-ms-win-core-path-HACK/blob/master/api-ms-win-core-path-blender.c#L161. I will delete some unsafe funcs and publish the code here.
![图片](https://github.com/user-attachments/assets/5ea70a8a-18b5-487e-9b98-d93455f4b1c0)

**Comment by dinkc64** [comment]
wow, nice!  I need this for ytdlp :)

**Comment by YuZhouRen86** [comment]
> wow, nice! I need this for ytdlp :)
Download dlls here and replace KxBase.dll in C:\Program Files\VxKex\Kex32 and  C:\Program Files\VxKex\Kex64. If you cannot replace, rename the old one and change new ones' name to KxBase.
[VxKex_Python_HACK.zip](https://github.com/user-attachments/files/18081446/VxKex_Python_HACK.zip)

**Comment by Aqua-Vision** [comment]
@YuZhouRen86 You are not to post unofficial files here. If you so need, create a fork and open a pull request. It is a security risk.

**Comment by YuZhouRen86** [comment]
> @YuZhouRen86 You are not to post unofficial files here. If you so need, create a fork and open a pull request. It is a security risk.

I am sorry to publish the unofficial files. This is a serious bug to Python developers such as me, it is caused by function pathcch.c/PathCchCombineEx. If you need any help, I am glad to help you.
