### ISSUE TITLE
LocalSend cannot run.

### ISSUE THREAD

**Issue by fukyou-fukme** [Aqua-Vision/MgKex#15]
![1](https://github.com/user-attachments/assets/9226369d-8028-44f9-a2e5-37473243f1bb)

Vxkex Log:
[localsend_app-00133791577498818359-1368.zip](https://github.com/user-attachments/files/18208230/localsend_app-00133791577498818359-1368.zip)

**Comment by Aqua-Vision** [comment]
This issue has been patched in the latest version of MgKex, not yet released. You may compile it yourself if necessary.
