### ISSUE TITLE
error when using the latest version

### ISSUE THREAD

**Issue by jih9uhuuh9** [Aqua-Vision/MgKex#3]
when using mgkex 1.1.1.1383, the latest version, i get an error when trying to run any app with it, bad image C:\windows\system32\kexdll.dll is either not designed to run on Windows or it contains an error., but older versions work fine, what to do? and i am trying to run geometry dash (doesnt run without a compatibilty layer)

**Comment by Aqua-Vision** [comment]
Please send your VxKex log files. I cannot reproduce this error.

**Comment by AbilioKID** [comment]
Sorry to butt in but I also noticed this issue. The problem is that the setup extracts an empty **kexdll.dll** (0 bytes). The debug version has the correct file.

**Comment by Aqua-Vision** [comment]
> Sorry to butt in but I also noticed this issue. The problem is that the setup extracts an empty **kexdll.dll** (0 bytes). The debug version has the correct file.

I just checked into this, you are correct. Please use the debug installer for MgKex. I must have used an installer I built at another time...

**Comment by Aqua-Vision** [comment]
Going to close this, I eventually figured out the problem. Latest release has been pulled.
