### ISSUE TITLE
Vivaldi browser

### ISSUE THREAD

**Issue by AbilioKID** [Aqua-Vision/MgKex#4]
Currently I'm using latest Vivaldi browser with a slighty updated version of VxKex (from CopperFr) and by changing the minor and major version with CEF Explorer.
I tried with your latest version, even with **kexdll.dll** issue fixed, and nothing works. Vivaldi doesn't even start nor does it give any error. Even without messing with minor and major versions.
Is there a known issue with Vivaldi and/or Chrome browsers I should be aware of?

**Comment by Aqua-Vision** [comment]
All types of chromium browsers are chaotic to get working. Can you please send your logs (%localappdata%\VxKex)?

**Comment by AbilioKID** [comment]
Thanks for replying. Unfortunently I uninstalled your version and went back to the one I was using (v1380 from CopperFr). It's based on v1375 with a few functions added. It works but I may later need other functions for other apps that I may try to use.
Unless you want a log from the one I'm using?
I'm used to Vivaldi but if it goes bad I can always start using Supermium.

If I have the time later, I'll try to re-install your version (or a new one if you meanwhile update it) and get fresh new logs.

**Comment by Aqua-Vision** [comment]
Same problem occured here:

https://github.com/Aqua-Vision/MgKex/issues/3
