### ISSUE TITLE
Add support for VirtualAlloc2

### ISSUE THREAD

**Issue by acyc070** [Aqua-Vision/MgKex#5]

**Comment by Aqua-Vision** [comment]
Noted. Please provide at least SOME description next time though. (I will get to this by the end of the week, maybe?) Thanks for pointing this out.

**Comment by acyc070** [comment]
duckstation requires it

**Comment by Aqua-Vision** [comment]
> duckstation requires it

Unlikely that this emulator would ever be supported with MgKex, but I'll give it a shot.
